In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("canada_per_capita_income.csv")
df.describe()

year  per capita income (US$)
count    47.000000                47.000000
mean   1993.000000             18920.137063
std      13.711309             12034.679438
min    1970.000000              3399.299037
25%    1981.500000              9526.914515
50%    1993.000000             16426.725480
75%    2004.500000             27458.601420
max    2016.000000             42676.468370

In [3]:
df.head()

year  per capita income (US$)
0  1970              3399.299037
1  1971              3768.297935
2  1972              4251.175484
3  1973              4804.463248
4  1974              5576.514583

In [12]:
X = df['year'].values
y = df['per capita income (US$)'].values
X = X.reshape(-1, 1)
model = linear_model.LinearRegression()
model.fit(X, y)

LinearRegression()

In [5]:
model.predict(X[[0]])

array([-134.55966672])

In [6]:
model.predict([[1970]])

array([-134.55966672])

In [7]:
m = model.coef_
b = model.intercept_
x = 1970
y = m*x+b
print(m, b)
print(y)

[828.46507522] -1632210.7578554575
[-134.55966672]


In [8]:
import pickle

In [9]:
with open('model_pickle', 'wb') as f:
    pickle.dump(model, f)

In [10]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [15]:
mp.predict([[2030]])

array([49573.34484664])